homework_57/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

webapp/urls.py
from django.urls import path
from webapp.views import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, \
    TaskDetailView, TaskCreateView, TaskDeleteView, TaskUpdateView, AddAuthorView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view()),
    path('projects/', ProjectListView.as_view(), name='home'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_edit'),
    path('projects/create/', ProjectCreateView.as_view(), name='add_project'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:pk>/tasks/add/', TaskCreateView.as_view(), name='add_task'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('tasks/<int:project_pk>/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_edit'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('projects/<int:pk>/users/update/', AddAuthorView.as_view(), name='update_user'),
]

webapp/models.py
from django.db import models
from .validators import validate_title, validate_description
from django.contrib.auth import get_user_model


class Status(models.Model):
    name = models.CharField(max_length=70, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=70, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок', validators=[validate_title])
    description = models.TextField(blank=True, null=True, verbose_name='Полное описание',
                                   validators=[validate_description])
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, verbose_name='Статус')
    types = models.ManyToManyField('webapp.Type', blank=True, related_name='tasks', verbose_name='Типы')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, verbose_name='Проект')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    edit_time = models.DateTimeField(auto_now=True, verbose_name='Время обновления')

    def __str__(self):
        return self.title


class Project(models.Model):
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')
    name = models.CharField(max_length=70, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    authors = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Авторы')

    def __str__(self):
        return self.name

templates/projects/add_project.html
{% extends 'base.html' %}
{% block main %}
    <h2>Создать Проект:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/project_form.html' %}
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:home' %}">Отмена</a>
{% endblock %}

templates/projects/home.html
{% extends 'base.html' %}
{% block menu %}
    {% if request.user.is_authenticated %}
        {% if perms.webapp.add_project or project.authors == request.user %}
                <a class="nav-link" href="{% url 'webapp:add_project' %}">Add Project</a>
        {% endif %}
    {% endif %}
{% endblock %}
{% block search %}
    <form method="get" class="d-flex">
        <div class="form-group">
            <input type="text" name="q" class="form-control" placeholder="Поиск" value="{{ search_form.q.value }}">
        </div>
        <button type="submit" class="ms-3 btn btn-primary">Найти</button>
    </form>
{% endblock %}
{% block main %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% if projects %}
        <h2 class="mb-4">Список Проектов:</h2>
        {% for project in projects %}
            <div class="project_card p-2 mb-3" style="text-align: center; border: 2px solid saddlebrown;
border-radius: 10px; background-color: antiquewhite; align-items: center">
                <a href="{% url 'webapp:project_detail' pk=project.pk %}"
                   style="color: saddlebrown; text-decoration: none"><h5><b>{{ project.name }}</b></h5></a>
                <span style="color: saddlebrown;">
                    Authors:
                    {% for author in project.authors.all %}
                        {{ author.username }}
                        {% if not forloop.last %},
                        {% endif %}
                    {% endfor %}
                </span>
            </div>
        {% endfor %}
    {% else %}
        <h3>Проектов не найдено.</h3>
    {% endif %}
{% endblock %}

templates/projects/project_delete.html
{% extends 'base.html' %}
{% block main %}
    <h3>Вы уверены, что хотите удалить проект "{{ project.name }}"?</h3>
    {% if has_tasks %}
        <p style="color: red">У проекта "{{ project.name }}" есть задачи. Удаление проекта также удалит все связанные задачи.</p>
    {% endif %}
        <form method="post" style="display: inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    <a class="btn btn-primary ms-3" href="{% url 'webapp:project_detail' pk=project.pk %}">Отмена</a>
{% endblock %}

templates/projects/project_detail.html
{% extends 'base.html' %}
{% block menu %}
    {% if request.user.is_authenticated %}
        {% if perms.webapp.add_task and user in project.authors.all %}
                <a class="nav-link" href="{% url 'webapp:add_task' pk=project.pk %}">Add Task</a>
        {% endif %}
    {% endif %}
{% endblock %}
{% block main %}
    <h1 class="mb-3">{{ project.name }}</h1>
    <b>Авторы:</b>
    <ul>
        {% for author in project.authors.all %}
            <li>{{ author.username }}</li>
        {% endfor %}
    </ul>
    {% if request.user.is_authenticated %}
        {% if perms.webapp.change_project and user in project.authors.all  %}
                <a class="btn btn-primary mb-3" href="{% url 'webapp:update_user' pk=project.pk %}">Изменить</a>
        {% endif %}
    {% endif %}

    <p><b>Дата начала:</b> {{ project.start_date }}</p>
    <p><b>Дата окончания:</b> {{ project.end_date }}</p>
    <p><b>Описание:</b><br> {{ project.description }}</p><br>
    <div class="project_link mb-4">
        {% if request.user.is_authenticated %}
            {% if perms.webapp.change_project and user in project.authors.all %}
                <a href="{% url 'webapp:project_edit' pk=project.pk %}" class="btn btn-primary">Изменить</a>
            {% endif %}
            {% if perms.webapp.delete_project and user in project.authors.all %}
                <a href="{% url 'webapp:project_delete' pk=project.pk %}" class="btn btn-danger ms-3">Удалить</a>
            {% endif %}
        {% endif %}
    </div>

    <h3 class="mb-4">Список задач для этого проекта:</h3>
    <div class="row row-cols-5 task_list">
        {% for task in tasks %}
            <div class="col">
                <div class="task p-2 my-3">
                    <div>
                        <h5>{{ task.title }}</h5>
                        <span>Status: {{ task.status.name }}</span><br>
                        <span>Type:
                            {% for type in task.types.all %}
                                {{ type.name }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </span><br>
                        <a href="{% url 'webapp:task_detail' pk=task.pk %}" style="color: saddlebrown">Details..</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <h3>Нет задач.</h3>
        {% endfor %}
    </div>
{% endblock %}

templates/projects/project_edit.html
{% extends 'base.html' %}
{% block main %}
    <h2>Редактировать Проект:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/project_form.html' %}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:project_detail' pk=project.pk %}">Отмена</a>
{% endblock %}