accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterUser

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='create_user')
]

homework_57/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

webapp/urls.py
from django.urls import path
from webapp.views import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, \
    TaskDetailView, TaskCreateView, TaskDeleteView, TaskUpdateView, AddAuthorView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view()),
    path('projects/', ProjectListView.as_view(), name='home'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_edit'),
    path('projects/create/', ProjectCreateView.as_view(), name='add_project'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:pk>/tasks/add/', TaskCreateView.as_view(), name='add_task'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('tasks/<int:project_pk>/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_edit'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('projects/<int:pk>/users/update/', AddAuthorView.as_view(), name='update_user'),
]

templates/add_author.html
{% extends 'base.html' %}
{% block main %}
  <h4>Изменение авторов в проекте "{{ project.name }}"</h4>
  <form method="post" style="display: inline">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Изменить</button>
  </form>
  <a class="btn btn-danger ms-3" href="{% url 'webapp:project_detail' pk=project.pk %}">Отмена</a>
{% endblock %}

templates/add_task.html
{% extends 'base.html' %}
{% block main %}
    <h2>Добавить Задачу:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/task_form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'home' %}">Отмена</a>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block title %}<title>Issue Tracker</title>{% endblock %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary p-3 mb-4">
        <div class="container">
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <div class="navbar-nav">
                    {% block menu %}
                    {% endblock %}
                    {% block log_in %}
                        {% if not request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Log in</a>
                            <a class="nav-link" href="{% url 'accounts:create_user' %}?next={{ request.get_full_path }}">Register</a>
                        {% else %}
                            <span class="nav-link ms-2">|</span>
                            <span class="nav-link"><b>{{ request.user }}</b></span>
                            <form method="post" action="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">
                                {% csrf_token %}
                                <button class="nav-link" type="submit">Log Out</button>
                            </form>
                        {% endif %}
                    {% endblock %}
                </div>
                {% block search %}
                {% endblock %}
            </div>
        </div>
    </nav>
{% endblock %}
<div class="container">
    {% block main %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>
</html>

templates/task_delete.html
{% extends 'base.html' %}

{% block main %}
  <h3 class="mb-4">Вы уверены, что хотите удалить задачу "{{ task.title }}"?</h3>
  <form style="display: inline" method="post" action="{% url 'task-delete' pk=task.pk %}">
      {% csrf_token %}
      <button class="btn btn-danger" type="submit">Удалить</button>
  </form>
  <a class="btn btn-primary ms-3" href="{% url 'task-detail' pk=task.pk %}">Отмена</a>
{% endblock %}

templates/task_detail.html
{% extends 'base.html' %}
{% block main %}
    <h3 class="mb-3">{{ task.title }}</h3>
    <p><b>Статус:</b> {{ task.status.name }}</p>
    <p><b>Тип:</b>
        {% for type in task.types.all %}
            {{ type.name }}{% if forloop.last %}.{% else %},{% endif %}
        {% endfor %}</p>
    <p><b>Полное описание:</b><br> {{ task.description }}</p><br>
    <a class="btn btn-danger" href="{% url 'task-delete' pk=task.pk %}">Удалить</a>
    <a class="btn btn-primary ms-3" href="{% url 'task-edit' pk=task.pk %}">Редактировать</a>
{% endblock %}

templates/task_edit.html
{% extends 'base.html' %}
{% block main %}
    <h2>Редактировать Задачу:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/task_form.html' %}
        <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'task-detail' pk=task.pk %}">Отмена</a>
{% endblock %}