homework_57/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

webapp/urls.py
from django.urls import path
from webapp.views import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, \
    TaskDetailView, TaskCreateView, TaskDeleteView, TaskUpdateView, AddAuthorView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view()),
    path('projects/', ProjectListView.as_view(), name='home'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_edit'),
    path('projects/create/', ProjectCreateView.as_view(), name='add_project'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:pk>/tasks/add/', TaskCreateView.as_view(), name='add_task'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('tasks/<int:project_pk>/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_edit'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('projects/<int:pk>/users/update/', AddAuthorView.as_view(), name='update_user'),
]

webapp/models.py
from django.db import models
from .validators import validate_title, validate_description
from django.contrib.auth import get_user_model


class Status(models.Model):
    name = models.CharField(max_length=70, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=70, verbose_name='Наименование')

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок', validators=[validate_title])
    description = models.TextField(blank=True, null=True, verbose_name='Полное описание',
                                   validators=[validate_description])
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, verbose_name='Статус')
    types = models.ManyToManyField('webapp.Type', blank=True, related_name='tasks', verbose_name='Типы')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, verbose_name='Проект')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    edit_time = models.DateTimeField(auto_now=True, verbose_name='Время обновления')

    def __str__(self):
        return self.title


class Project(models.Model):
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')
    name = models.CharField(max_length=70, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    authors = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Авторы')

    def __str__(self):
        return self.name

templates/tasks/add_task.html
{% extends 'base.html' %}
{% block main %}
    <h2>Добавить Задачу:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/task_form.html' %}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:project_detail' pk=project.pk %}">Отмена</a>
{% endblock %}

templates/tasks/task_delete.html
{% extends 'base.html' %}

{% block main %}
  <h3 class="mb-4">Вы уверены, что хотите удалить задачу "{{ task.title }}"?</h3>
  <form style="display: inline" method="post" action="{% url 'webapp:task_delete' pk=task.pk %}">
      {% csrf_token %}
      <button class="btn btn-danger" type="submit">Удалить</button>
  </form>
  <a class="btn btn-primary ms-3" href="{% url 'webapp:task_detail' pk=task.pk %}">Отмена</a>
{% endblock %}

templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block menu %}
    <a href="{% url 'webapp:project_detail' pk=project.pk %}" class="nav-link">Project</a>
{% endblock %}
{% block main %}
    <h3 class="mb-3">{{ task.title }}</h3>
    <p><b>Статус:</b> {{ task.status.name }}</p>
    <p><b>Тип:</b>
        {% for type in task.types.all %}
            {{ type.name }}{% if forloop.last %}.{% else %},{% endif %}
        {% endfor %}</p>
    <p><b>Полное описание:</b><br> {{ task.description }}</p>
    {% if request.user.is_authenticated %}
        {% if perms.webapp.change_task and user in project.authors.all %}
                <a class="btn btn-primary" href="{% url 'webapp:task_edit' pk=task.pk project_pk=project.pk%}">Изменить</a>
        {% endif %}
        {% if perms.webapp.delete_task and user in project.authors.all %}
                <a class="btn btn-danger ms-3" href="{% url 'webapp:task_delete' pk=task.pk %}">Удалить</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/tasks/task_edit.html
{% extends 'base.html' %}
{% block main %}
    <h2>Редактировать Задачу:</h2>
    <form method="post" style="display: inline">
        {% csrf_token %}
        {% include 'partial/task_form.html' %}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:task_detail' pk=task.pk %}">Отмена</a>
{% endblock %}